version: '3.8'
services:
  kumbia:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8001"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'ChangeMe24k!'
